version: '3.1'

services:
  api:
    container_name: api
    image: node:12
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: bash -c 'yarn && yarn start:dev'
    links:
      - db
    depends_on:
      - db
    restart: always

  db:
    container_name: db
    image: postgres:12
    env_file:
      - .env.development.local
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
